name: CI/CD

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  run-testbed:
    # env:
    #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    #   DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Debug 
        run: |
          pwd
          ls -la 

      - uses: actions/checkout@v3
        with:
          repository: edigonzales/dmav-validierungsmodell-testbed
          path: tools

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Debug 
        working-directory: tools
        run: |
          pwd
          ls -la

      - name: Run testbed 
        working-directory: tools
        run: |
          ./gradlew -i runProgram -PilivalidatorVersion=1.14.3 -Pdata=../data/Validierungsmodell -Pconfig=../model/DMAV_V1_0_Validierung.ini -Pmodeldir=../model

      - uses: actions/upload-artifact@v4
        with:
          name: testbed.log
          path: testbed.log

      # - name: Build 
      #   run: |
      #     ./gradlew clean build -x test
      #     ls -la build/libs

      # - name: Login to Docker Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ env.DOCKER_USERNAME }}
      #     password: ${{ env.DOCKER_PASSWORD }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build Docker Image 
      #   run: |
      #     ./gradlew buildAndPushMultiArchImage

